
version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-autotestai}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-autotestai_pass}
      - POSTGRES_DB=${POSTGRES_DB:-autotestai_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build: ./frontend
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    command: ["npm", "run", "dev"]

volumes:
  pgdata:
  redisdata:
