
name: CI/CD Deploy
on: push:
  branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Frontend
        uses: actions/setup-node@v4
        with: node-version: '18'
      - name: Frontend build
        run: |
          cd frontend
          npm ci
          npm run build
      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: false
